/*
 * Copyright 2021, 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);



void BOARD_InitTPMPins(void);


#define PTB0_PIN					0
#define PTB0_GPIO				    GPIOB
#define PTB0_PORT					PORTB

#define PTB1_PIN					1
#define PTB1_GPIO					GPIOB
#define PTB1_PORT					PORTB

#define PTB2_PIN					2
#define PTB2_GPIO					GPIOB
#define PTB2_PORT					PORTB

void BOARD_InitHallPins(void);


void BOARD_InitADCPin(void);


void BOARD_InitLPCMPin(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
